language: node_js
node_js:
- 4.3.2
sudo: false
install:
  - npm install
script:
  - npm run lint
  - istanbul cover node_modules/.bin/_mocha test/plugin-test.js && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  